# Generated by Django 3.2 on 2022-09-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studygroup_id', models.CharField(max_length=20)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chatroom')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.material')),
                ('studygroup_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.account')),
            ],
        ),
        migrations.CreateModel(
            name='StudyEnroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.account')),
                ('studygroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.account')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_code', models.CharField(max_length=20)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='backend.account')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='backend.account')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.account'),
        ),
        migrations.CreateModel(
            name='CourseEnroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.account')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='backend.account'),
        ),
        migrations.AddField(
            model_name='course',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta', to='backend.account'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chatroom_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.account'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.message'),
        ),
    ]
