# Generated by Django 3.2 on 2022-09-27 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220926_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='material',
        ),
        migrations.AddField(
            model_name='material',
            name='studygroup_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.studygroup'),
        ),
        migrations.AlterField(
            model_name='studyenroll',
            name='studygroup_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.studygroup'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='studygroup_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
