# Generated by Django 3.2 on 2022-09-27 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220926_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.message'),
        ),
    ]
