# Generated by Django 3.2 on 2022-10-06 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220926_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='material',
            name='studygroup_id',
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('EXAM', 'Exam'), ('STUDYGUIDE', 'Studyguide'), ('HOMEWORK', 'Homework'), ('DISSCUSSION_POST', 'Disscussion Post')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='topic',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='chatroom_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='invite_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('studygroup_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='backend.account')),
                ('friends_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_with', to='backend.account')),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_id', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('studygroup_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.studygroup')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='module_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.module'),
        ),
    ]
