# Generated by Django 3.2 on 2022-10-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20221005_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('EXAM', 'Exam'), ('STUDYGUIDE', 'Studyguide'), ('HOMEWORK', 'Homework'), ('DISSCUSSION_POST', 'Disscussion Post')], max_length=20, null=True),
        ),
    ]
