# Generated by Django 3.2 on 2022-10-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_material_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
