# Generated by Django 3.2 on 2022-10-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_account_somenewfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='stdygroup_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
