# Generated by Django 3.2 on 2022-10-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_studygroup_stdygroup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='stdygroup_name',
            new_name='studygroup_name',
        ),
    ]
