# Generated by Django 3.2 on 2022-10-24 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_stdygroup_name_studygroup_studygroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.account'),
        ),
    ]
