# Generated by Django 3.2 on 2022-10-26 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_owner', to='backend.account'),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='backend.account'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta', to='backend.account'),
        ),
    ]
