# Generated by Django 3.2 on 2022-10-31 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20221026_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='announcement_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.account'),
        ),
        migrations.AddField(
            model_name='invite',
            name='invite_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
