# Generated by Django 3.2 on 2022-10-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20221031_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='announcement_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='studygroup_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
