# Generated by Django 3.2 on 2022-11-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_account_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='file_content',
            new_name='file_content_upload',
        ),
    ]
