# Generated by Django 3.2 on 2022-12-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20221208_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file_content_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
