# Generated by Django 3.2 on 2022-12-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_material_file_content_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.TextField(default='N/A', null=True)),
                ('description', models.TextField(default='N/A', null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('recommendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.account')),
            ],
        ),
    ]
